#!/bin/sh

#ToDo: unset PETSC_DIR, PETSC_ARCH, and SLEPC_DIR

#ToDo: may need to set the environment variable QT_QPA_PLATFORM=xcb to force X11 and avoid issues with Wayland

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
DOWNLOAD_DIR="../external_packages"

#----------------------------------------------------
# GNU keyring for verifying GNU packages
#----------------------------------------------------

# GNU_KEYRING downloaded from:
# wget https://ftp.gnu.org/gnu/gnu-keyring.gpg

GNU_KEYRING="$SCRIPT_DIR/keyrings/gnu-keyring.gpg"
MADLER_KEYRING="$SCRIPT_DIR/keyrings/madler-keyring.gpg"
AKHUZHIN_KEYRING="$SCRIPT_DIR/keyrings/akhuzhin-keyring.gpg"
WLEMBERG_KEYRING="$SCRIPT_DIR/keyrings/wlemberg-keyring.gpg"
ACOOPERSMITH_KEYRING="$SCRIPT_DIR/keyrings/acoopersmith-keyring.gpg"
ACOOPERSMITH2_KEYRING="$SCRIPT_DIR/keyrings/acoopersmith2-keyring.gpg"
MTURNER_KEYRING="$SCRIPT_DIR/keyrings/mturner-keyring.gpg"
AJACKSON_KEYRING="$SCRIPT_DIR/keyrings/ajackson-keyring.gpg"
SMCVITTIE_KEYRING="$SCRIPT_DIR/keyrings/smcvittie-keyring.gpg"
ICUROBOT_KEYRING="$SCRIPT_DIR/keyrings/icurobot-keyring.gpg"

#----------------------------------------------------
# download required packages
#----------------------------------------------------

download_package_and_verify_sha ()
{
    PACKAGE="$1"
    URL="$2"
    EXPECTED_SHA="$3"

    FILE="$DOWNLOAD_DIR/$PACKAGE"

    if [ ! -f "$FILE" ]; then
        echo "Downloading package file $PACKAGE ..."
        wget -O "$FILE" "$URL" || return 1
    fi

    echo "Verifying SHA for $PACKAGE ..."

    ACTUAL_SHA=$(shasum "$FILE" | awk '{print $1}')

    if [ "$ACTUAL_SHA" != "$EXPECTED_SHA" ]; then
        echo "ERROR: SHA mismatch for $PACKAGE"
        echo "Expected: $EXPECTED_SHA"
        echo "Actual:   $ACTUAL_SHA"
        return 1
    fi

    echo "SHA OK: $PACKAGE"
    echo ""
}

download_package_and_verify_sha256 ()
{
    PACKAGE="$1"
    URL="$2"
    EXPECTED_SHA256="$3"

    FILE="$DOWNLOAD_DIR/$PACKAGE"

    if [ ! -f "$FILE" ]; then
        echo "Downloading package file $PACKAGE ..."
        wget -O "$FILE" "$URL" || return 1
    fi

    echo "Verifying SHA-256 for $PACKAGE ..."

    ACTUAL_SHA256=$(sha256sum "$FILE" | awk '{print $1}')

    if [ "$ACTUAL_SHA256" != "$EXPECTED_SHA256" ]; then
        echo "ERROR: SHA-256 mismatch for $PACKAGE"
        echo "Expected: $EXPECTED_SHA256"
        echo "Actual:   $ACTUAL_SHA256"
        return 1
    fi

    echo "SHA-256 OK: $PACKAGE"
    echo ""
}

download_package_and_verify_sig ()
{
    PACKAGE="$1"
    URL="$2"
    SIG_SUFFIX="${3:-sig}"
    KEYRING="$4"
    SITE_SUFFIX="$5"

    FILE="$DOWNLOAD_DIR/$PACKAGE"
    SIG="$FILE.$SIG_SUFFIX"

    if [ ! -f "$FILE" ]; then
        echo "Downloading package file $PACKAGE ..."
        wget -O "$FILE" "${URL}$SITE_SUFFIX" || return 1
    fi

    #echo "List of keys for $KEYRING:"
    #gpg --no-default-keyring \
    #    --keyring "$KEYRING" \
    #    --list-keys

    if [ ! -f "$SIG" ]; then
        echo "Downloading sig file $PACKAGE.$SIG_SUFFIX ..."
        wget -O "$SIG" "${URL}.$SIG_SUFFIX$SITE_SUFFIX" || return 1
    fi

    echo "Verifying $PACKAGE ..."
    gpgv --keyring "$KEYRING" "$SIG" "$FILE" || return 1

    echo "Signature OK: $PACKAGE"
    echo ""
}

#----------------------------------------------------
# local gcc compile version for portable pre-compiled binaries
#----------------------------------------------------

gcc_version="gcc-13.3.0"

#----------------------------------------------------
# packages downloaded by petsc
#----------------------------------------------------

fblaslapack="https://bitbucket.org/petsc/pkg-fblaslapack/get/v3.4.2-p3.tar.gz"
metis="https://bitbucket.org/petsc/pkg-metis/get/v5.1.0-p12.tar.gz"
mumps="https://web.cels.anl.gov/projects/petsc/download/externalpackages/MUMPS_5.7.3.tar.gz"
scalapack="https://github.com/Reference-ScaLAPACK/scalapack/archive/v2.2.2.tar.gz"
scotch="https://gitlab.inria.fr/scotch/scotch/-/archive/v7.0.6/scotch-v7.0.6.tar.gz"
cmake="https://github.com/Kitware/CMake/releases/download/v3.31.6/cmake-3.31.6.tar.gz"

# Compile HYPRE separately because PETSc would compile it for complex, which
# is incompatible with MFEM.

#----------------------------------------------------
# packages to install
#----------------------------------------------------

with_meson=1
with_xcb=1
with_freetype=1
with_tcl=1
with_tk=1
with_occt=1
with_gmsh=1
with_qt=1
with_m4=1
with_bison=1
with_zlib=1
with_flex=1
with_hwloc=1
with_libevent=1
with_pmix=1
with_prrte=1
with_openmpi=1
with_mpich=0
with_hypre=1
with_cmake=1
with_petsc=1
with_mfem=1
with_OpenParEM=1
with_OpenParEMg=1

#----------------------------------------------------
# library types
#----------------------------------------------------

# openmpi requires shared build at this time

enable_static=no
enable_shared=yes

#----------------------------------------------------
# check that the script is being run from scripts
#----------------------------------------------------

if [ ! -f "OpenParEM_build" ]; then
   echo "ERROR: OpenParEM_build must be run from the scripts directory"
   exit 1
fi

#----------------------------------------------------
# check for installed tools
#----------------------------------------------------

which cmake > /dev/null 2>&1
if [ $? -eq 0 ]; then
   with_cmake=0
fi

which bison > /dev/null 2>&1
if [ $? -eq 0 ]; then
   with_bison=0
fi

which flex > /dev/null 2>&1
if [ $? -eq 0 ]; then
   with_flex=0
fi

which mpirun > /dev/null 2>&1
if [ $? -eq 0 ]; then
   with_openmpi=0
   with_mpich=0
fi

#----------------------------------------------------
# subroutines
#----------------------------------------------------

scripts_dir=$PWD

# unpack file name for external packages
FILE_base=""

# unpack a tarball and cd to the directory
unpack_and_enter() {

   FILE=$1

   # check for existence
   if [ ! -f "$FILE" ]; then
      echo "ERROR: distribution \"""$FILE""\" not found in $PWD"
      exit 1
   fi

   # determine type and base name

   is_identified=0

   is_targz=0
   if [ "$is_identified" = "0" ]; then
      FILE_base=${FILE%.tar.gz}
      if [ "$FILE_base" != "$FILE" ]; then
         is_targz=1
         is_identified=1
      fi
   fi

   is_tarxz=0
   if [ "$is_identified" = "0" ]; then
      FILE_base=${FILE%.tar.xz}
      if [ "$FILE_base" != "$FILE" ]; then
         is_tarxz=1
         is_identified=1
      fi
   fi

   is_tgz=0
   if [ "$is_identified" = "0" ]; then
      FILE_base=${FILE%.tgz}
      if [ "$FILE_base" != "$FILE" ]; then
         is_tgz=1
         is_identified=1
      fi
   fi

   is_zip=0
   if [ "$is_identified" = "0" ]; then
      FILE_base=${FILE%.zip}
      if [ "$FILE_base" != "$FILE" ]; then
         is_zip=1
         is_identified=1
      fi
   fi

   if [ "$is_identified" = "0" ]; then
      echo "ERROR: unrecognized distribution for \"""$FILE""\""
      exit 1
   fi

   # tcl and tk add "-src" to the tarball name that must be removed to get the correct base name

   prefix=`echo $FILE_base | cut -c1-3`
   if [ "$prefix" = "tcl" ]; then
      FILE_base=${FILE_base%-src}
   fi

   prefix=`echo $FILE_base | cut -c1-2`
   if [ "$prefix" = "tk" ]; then
      FILE_base=${FILE_base%-src}
   fi

   # remove any previously unpacked instance
   if [ -d "$FILE_base" ]; then
      rm -Rf "$FILE_base"
      if [ $? -ne 0 ]; then
         echo "ERROR: unable to remove directory \"""$FILE_base""\""
      fi
   fi

   # unpack

   if [ "$is_targz" = "1" -o "$is_tgz" = "1" -o "$is_tarxz" = "1" ]; then
      tar -xf "$FILE"
      if [ $? -ne 0 ]; then
         echo "ERROR: failure to unpack \"""$FILE""\""
         exit 1
      fi
   fi

   if [ "$is_zip" = "1" ]; then
      unzip "$FILE"
      if [ $? -ne 0 ]; then
         echo "ERROR: failure to unpack \"""$FILE""\""
         exit 1
      fi
   fi

   # make sure it unpacked
   if [ ! -d "$FILE_base" ]; then
      echo "ERROR: failure to unpack \"""$FILE""\""
      exit 1
   fi

   cd "$FILE_base"
}

remove_base_directory() {
   if [ -d "$FILE_base" ]; then
      rm -Rf "$FILE_base"
      if [ $? -ne 0 ]; then
         echo "ERROR: failed to remove directory \"""$FILE_base""\""
         exit 1
      fi
   else 
      echo "ERROR: failed to find directory \"""$FILE_base""\""
      exit 1
   fi
}

wrap_executable() {

   echo "wrapping $1"

   # executable to wrap
   PROG=$1
   BINPROG=$PROG.bin

   # flag for processing for OPENMPI
   HAS_COMPILED_OPENMPI=$2

   # delete the log file
   REMOVE_LOGFILE=$3

   # redirect stdout/stderr to a log file
   TEST_REDIRECT=$4

   cd "$install_path/bin"

      if [ $? -ne 0 ]; then
         echo "ERROR: failed to change to the bin directory"
         exit 1
      fi

      mv $PROG $BINPROG
      if [ $? -ne 0 ]; then
         echo "ERROR: failed to move $PROG to $BINPROG"
         exit 1
      fi

      echo '#!/bin/sh' > $PROG
      if [ $? -ne 0 ]; then
         echo "ERROR: failed to create $PROG"
         exit 1
      fi

      echo '' >> $PROG
      if [ "$TEST_REDIRECT" = "1" ]; then
         echo "# usage: $PROG [-h|--help] project_name log_file_name" >> $PROG
         echo '#        project_name is required and requires an extension' >> $PROG
         echo '#        log_file_name is optional' >> $PROG
         echo '# ' >> $PROG
         echo '# Output to the terminal is redirected to a log file, where' >> $PROG
         echo "# the file name is either log_file_name or $PROG.log if log_file_name is not provided." >> $PROG
         echo '# ' >> $PROG
         echo '# If -h or --help are given, then a short help message is printed to the terminal' >> $PROG
         echo '# followed by immediate exit.' >> $PROG
      else
         echo "# usage: $PROG file_name" >> $PROG
         echo '#        file_name is required' >> $PROG
      fi

      echo '' >> $PROG
      echo "BINPROG=$BINPROG" >> $PROG
      echo 'BINPATH=$(which $BINPROG)' >> $PROG
      echo 'if [ "$BINPATH" = "" ]; then' >> $PROG
      echo '   echo "ERROR: Failed to locate $BINPROG."' >> $PROG
      echo '   exit 1' >> $PROG
      echo 'fi' >> $PROG

      if [ "$TEST_REDIRECT" = "1" ]; then
         echo '' >> $PROG
         echo 'if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then' >> $PROG
         echo '   $BINPROG "$1"' >> $PROG
         echo '   exit 0' >> $PROG
         echo 'fi' >> $PROG
      fi

      echo 'OPEM=${BINPATH%/bin/$BINPROG}' >> $PROG

      echo '' >> $PROG
      echo 'export LD_LIBRARY_PATH=$OPEM/lib:$OPEM/lib64:$LD_LIBRARY_PATH' >> $PROG
      if [ "$HAS_COMPILED_OPENMPI" = "1" ]; then
         echo 'export OPAL_PREFIX=$OPEM' >> $PROG
         echo 'export PMIX_PREFIX=$OPEM' >> $PROG
      fi
      echo 'export OMP_NUM_THREADS=1' >> $PROG
      echo 'export QT_QPA_PLATFORM=xcb' >> $PROG
      echo 'export QT_QPA_PLATFORMTHEME=generic' >> $PROG


      # create a default log file name if one is not provided
      # default is to remove any exension and add .log (aligned with OpenParEM3D)
      echo '' >> $PROG
      echo 'if [ "$2" = "" ]; then' >> $PROG
      echo "   LOGFILE=\`expr \"\$1\" : '\\(.*\\)\\.[^.]*\$'\`.log" >> $PROG
      echo 'else' >> $PROG
      echo '   LOGFILE="$2"' >> $PROG
      echo 'fi' >> $PROG
      echo '' >> $PROG


      echo '' >> $PROG
      echo 'HASLOGFILE=0' >> $PROG
      echo 'if [ "$2" != "" ]; then' >> $PROG
      echo '   HASLOGFILE=1' >> $PROG
      echo 'fi' >> $PROG
      echo '' >> $PROG

      if [ "$REMOVE_LOGFILE" = "1" ]; then
         echo 'if [ -n "$OMPI_COMM_WORLD_RANK" ]; then' >> $PROG
         echo '     # Open MPI' >> $PROG
         echo '    RANK=$OMPI_COMM_WORLD_RANK' >> $PROG
         echo 'elif [ -n "$PMI_RANK" ]; then' >> $PROG
         echo '    # MPICH, Intel MPI, many PMI-based launchers' >> $PROG
         echo '    RANK=$PMI_RANK' >> $PROG
         echo 'elif [ -n "$MPI_RANKID" ]; then' >> $PROG
         echo '    # Some older MPICH / platform MPI variants' >> $PROG
         echo '    RANK=$MPI_RANKID' >> $PROG
         echo 'elif [ -n "$SLURM_PROCID" ]; then' >> $PROG
         echo '    # Slurm srun' >> $PROG
         echo '    RANK=$SLURM_PROCID' >> $PROG
         echo 'else' >> $PROG
         echo '    RANK=0' >> $PROG
         echo 'fi' >> $PROG
         echo '' >> $PROG
         echo 'if [ "$RANK" = "0" ]; then' >> $PROG
         echo '   rm -f "$LOGFILE"' >> $PROG
         echo 'fi' >> $PROG
         echo '' >> $PROG
      fi

      if [ "$TEST_REDIRECT" = "1" ]; then
         echo 'if [ "$HASLOGFILE" = "1" ]; then' >> $PROG
         echo '   $BINPROG "$@" >> "$LOGFILE" 2>&1' >> $PROG
         echo 'else' >> $PROG
         echo '   $BINPROG "$@"' >> $PROG
         echo 'fi' >> $PROG
      else
         echo '$BINPROG "$@"' >> $PROG
      fi

      chmod u+x $PROG
      if [ $? -ne 0 ]; then
         echo "ERROR: failed make $PROG executable"
         exit 1
      fi

   cd "$scripts_dir"
}

#----------------------------------------------------
# variables
#----------------------------------------------------

# start time
start_time="$(date -u +%s)"

print_help=0
retval=0
show_setup=0
clean_in_place=0
precompiled_bin=0

cd ..
install_path=$PWD
cd "$scripts_dir"
jobs=1

export PKG_CONFIG_PATH="$install_path/lib/pkgconfig:$install_path/lib/x86_64-linux-gnu/pkgconfig:$install_path/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"

# convenience variable for simplifying command line options
with_gui=0

#----------------------------------------------------
# input processing
#----------------------------------------------------

for arg in "$@"; do
   if [ "$arg" = "-H" -o "$arg" = "--help" ]; then
      print_help=1
   else
      keyword=${arg%=*}
      value=${arg#"$keyword="} 

      if [ "$keyword" = "--prefix" ]; then
         install_path=$value
      elif [ "$keyword" = "--jobs" ]; then
         jobs=$value
#      elif [ "$arg" = "--static" ]; then
#         enable_static=yes
#         enable_shared=no
      elif [ "$arg" = "--without-all" ]; then
         with_meson=0
         with_xcb=0
         with_freetype=0
         with_tcl=0
         with_tk=0
         with_occt=0
         with_gmsh=0
         with_qt=0
         with_m4=0
         with_bison=0
         with_zlib=0
         with_flex=0
         with_hwloc=0
         with_libevent=0
         with_pmix=0
         with_prrte=0
         with_openmpi=0
         with_mpich=0
         with_hypre=0
         with_cmake=0
         with_petsc=0
         with_mfem=0
         with_OpenParEM=0
         with_OpenParEMg=0
      elif [ "$arg" = "--with-all" ]; then
         with_meson=1
         with_xcb=1
         with_freetype=1
         with_tcl=1
         with_tk=1
         with_occt=1
         with_gmsh=1
         with_qt=1
         with_m4=1
         with_bison=1
         with_zlib=1
         with_flex=1
         with_hwloc=1
         with_libevent=1
         with_pmix=1
         with_prrte=1
         with_openmpi=1
         with_mpich=0
         with_hypre=1
         with_cmake=1
         with_petsc=1
         with_mfem=1
         with_OpenParEM=1
         with_OpenParEMg=1
      elif [ "$arg" = "--show-setup" ]; then
         show_setup=1
      elif [ "$arg" = "--clean-in-place" ]; then
         clean_in_place=1
      elif [ "$arg" = "--precompiled-bin" ]; then
         precompiled_bin=1
         clean_in_place=1

      elif [ "$arg" = "--with-freetype" ]; then
         with_freetype=1
      elif [ "$keyword" = "--with-freetype" ]; then
         with_freetype=1
         freetype=$value
      elif [ "$arg" = "--without-freetype" ]; then
         with_freetype=0
      elif [ "$arg" = "--with-meson" ]; then
         with_meson=1
      elif [ "$keyword" = "--with-meson" ]; then
         with_meson=1
         meson=$value
      elif [ "$arg" = "--without-meson" ]; then
         with_meson=0
      elif [ "$arg" = "--with-xcb" ]; then
         with_xcb=1
      elif [ "$keyword" = "--with-xcb" ]; then
         with_xcb=1
         xcb=$value
      elif [ "$arg" = "--without-xcb" ]; then
         with_xcb=0
      elif [ "$arg" = "--with-tcl" ]; then
         with_tcl=1
      elif [ "$keyword" = "--with-tcl" ]; then
         with_tcl=1
         tcl=$value
      elif [ "$arg" = "--without-tcl" ]; then
         with_tcl=0
      elif [ "$arg" = "--with-tk" ]; then
         with_tk=1
      elif [ "$keyword" = "--with-tk" ]; then
         with_tk=1
         tk=$value
      elif [ "$arg" = "--without-tk" ]; then
         with_tk=0
      elif [ "$arg" = "--with-occt" ]; then
         with_occt=1
      elif [ "$keyword" = "--with-occt" ]; then
         with_occt=1
         occt=$value
      elif [ "$arg" = "--without-occt" ]; then
         with_occt=0
      elif [ "$arg" = "--with-gmsh" ]; then
         with_gmsh=1
      elif [ "$keyword" = "--with-gmsh" ]; then
         with_gmsh=1
         gmsh=$value
      elif [ "$arg" = "--without-gmsh" ]; then
         with_gmsh=0
      elif [ "$arg" = "--with-qt" ]; then
         with_qt=1
      elif [ "$keyword" = "--with-qt" ]; then
         with_qt=1
         qt=$value
      elif [ "$arg" = "--without-qt" ]; then
         with_qt=0
      elif [ "$arg" = "--with-m4" ]; then
         with_m4=1
      elif [ "$keyword" = "--with-m4" ]; then
         with_m4=1
         m4=$value
      elif [ "$arg" = "--without-m4" ]; then
         with_m4=0
      elif [ "$arg" = "--with-bison" ]; then
         with_bison=1
      elif [ "$keyword" = "--with-bison" ]; then
         with_bison=1
         bison=$value
      elif [ "$arg" = "--without-bison" ]; then
         with_bison=0
      elif [ "$arg" = "--with-zlib" ]; then
         with_zlib=1
      elif [ "$keyword" = "--with-zlib" ]; then
         with_zlib=1
         zlib=$value
      elif [ "$arg" = "--without-zlib" ]; then
         with_zlib=0
      elif [ "$arg" = "--with-flex" ]; then
         with_flex=1
      elif [ "$keyword" = "--with-flex" ]; then
         with_flex=1
         flex=$value
      elif [ "$arg" = "--without-flex" ]; then
         with_flex=0
      elif [ "$arg" = "--with-hwloc" ]; then
         with_hwloc=1
      elif [ "$keyword" = "--with-hwloc" ]; then
         with_hwloc=1
         hwloc=$value
      elif [ "$arg" = "--without-hwloc" ]; then
         with_hwloc=0
      elif [ "$arg" = "--with-libevent" ]; then
         with_libevent=1
      elif [ "$keyword" = "--with-libevent" ]; then
         with_libevent=1
         libevent=$value
      elif [ "$arg" = "--without-libevent" ]; then
         with_libevent=0
      elif [ "$arg" = "--with-pmix" ]; then
         with_pmix=1
      elif [ "$keyword" = "--with-pmix" ]; then
         with_pmix=1
         pmix=$value
      elif [ "$arg" = "--without-pmix" ]; then
         with_pmix=0
      elif [ "$arg" = "--with-prrte" ]; then
         with_prrte=1
      elif [ "$keyword" = "--with-prrte" ]; then
         with_prrte=1
         prrte=$value
      elif [ "$arg" = "--without-prrte" ]; then
         with_prrte=0
      elif [ "$arg" = "--with-openmpi" ]; then
         with_openmpi=1
      elif [ "$keyword" = "--with-openmpi" ]; then
         with_openmpi=1
         openmpi=$value
      elif [ "$arg" = "--without-openmpi" ]; then
         with_openmpi=0
      elif [ "$arg" = "--with-mpich" ]; then
         with_mpich=1
      elif [ "$keyword" = "--with-mpich" ]; then
         with_mpich=1
         mpich=$value
      elif [ "$arg" = "--without-mpich" ]; then
         with_mpich=0
      elif [ "$arg" = "--with-hypre" ]; then
         with_hypre=1
      elif [ "$keyword" = "--with-hypre" ]; then
         with_hypre=1
         hypre=$value
      elif [ "$arg" = "--without-hypre" ]; then
         with_hypre=0
      elif [ "$arg" = "--with-cmake" ]; then
         with_cmake=1
      elif [ "$keyword" = "--with-cmake" ]; then
         with_cmake=1
         cmake=$value
      elif [ "$arg" = "--without-cmake" ]; then
         with_cmake=0
      elif [ "$arg" = "--with-petsc" ]; then
         with_petsc=1
      elif [ "$keyword" = "--with-petsc" ]; then
         with_petsc=1
         petsc=$value
      elif [ "$arg" = "--without-petsc" ]; then
         with_petsc=0
      elif [ "$arg" = "--with-mfem" ]; then
         with_mfem=1
      elif [ "$keyword" = "--with-mfem" ]; then
         with_mfem=1
         mfem=$value
      elif [ "$arg" = "--without-mfem" ]; then
         with_mfem=0
      elif [ "$arg" = "--with-OpenParEM" ]; then
         with_OpenParEM=1
      elif [ "$arg" = "--without-OpenParEM" ]; then
         with_OpenParEM=0
      elif [ "$arg" = "--with-OpenParEMg" ]; then
         with_OpenParEMg=1
      elif [ "$arg" = "--without-OpenParEMg" ]; then
         with_OpenParEMg=0
      elif [ "$arg" = "--with-gui" ]; then
         with_gui=1
      elif [ "$arg" = "--without-gui" ]; then
         with_gui=0
      else
         echo "ERROR: unrecognized option ""$arg"
         exit 1
      fi
   fi
done

#----------------------------------------------------
# print help
#----------------------------------------------------

if [ $print_help -eq 1 ]; then
   echo "Usage: OpenParEM_build [OPTIONS]"
   echo "Builds the OpenParEM distribution when run from the scripts directory."
   echo ""
   echo "The build tools make, g++, gfortran, and perl must be installed on the system."
   echo ""
   echo "For an in-place build with the results placed in the distribution tree, execute as"
   echo "   shell: OpenParEM_build --jobs=N --with-all"
   echo "If OpenParEM_build has already been run, use the --clean-in-place option to delete"
   echo "any prior results before compiling."
   echo ""
   echo "For an out-of-place build in a given install directory, execute as"
   echo "   shell: OpenParEM_build --jobs=N --prefix=install_dir --with-all"
   echo "where the installation directory must already exist.  Note that there is no option for"
   echo "deleting prior results on additional build runs."
   echo ""
   echo "Omit the --with-all option, then if cmake, flex, or bison are found using a search with"
   echo "the existing PATH, they are compiled and installed from source."
   echo ""
   echo "If an MPI development distribution is not found at /usr/bin, /usr/lib, and /usr/include, then"
   echo "Open MPI is compiled and installed from source. An option can be applied to force the compilation."
   echo ""
   echo "After compiling, tests are performed on OpenParEM2D and OpenParEM3D.  If these pass,"
   echo "then compilation is successful and OpenParEM is ready to use.  However, it is still required"
   echo "to set the PATH."
   echo ""
   echo "common OPTIONS:"
   echo "  --help or -H             print this help message and exit"
   echo "  --prefix=path            set the install path to the given path.  Default is the current working directory"
   echo "  --jobs=integer           execute make with parallel processing [i.e. make -j integer]. Default=1"
#   echo "  --shared                  build using shared libraries. Default is to build static libraries whenever possible"
   echo "  --clean-in-place         remove any prior in-place installation"
   echo "  --with-all               compile everything to minimize potential compatibility issues"
   echo "  --with-gui               compile the libraries needed for the GUI"
   echo "  --show-setup             show the compilation setup and exit"
   echo ""
   echo "advanced OPTIONS:"
   echo "  --without-all            skip compiling all; generally followed by --with-* options to add back in something to compile"
#   echo "  --with-gui               compile the libraries needed for the GUI"
#   echo "  --without-gui            do not compile the libraries needed for the GUI (default)"
   echo "  --with-freetype=file]    compile freetype using the default distribution or the provided file"
   echo "  --with-meson=[file]      compile meson and ninja  using the default distribution or the provided file"     
   echo "  --with-xcb=file]         compile xcb using the default distribution or the provided file"
   echo "  --with-tcl=file]         compile tcl using the default distribution or the provided file"
   echo "  --with-tk[=file]         compile tk using the default distribution or the provided file"
   echo "  --with-occt[=file]       compile occt using the default distribution or the provided file"
   echo "  --with-gmsh[=file]       compile gmsh using the default distribution or the provided file"
   echo "  --with-qt[=file]         compile qt using the default distribution or the provided file"
   echo "  --with-m4[=file]         compile m4 using the default distribution or the provided file"
   echo "  --without-m4             skip compiling m4"
   echo "  --with-bison[=file]      compile bison using the default distribution or the provided file"
   echo "  --without-bison          skip compiling bison"
   echo "  --with-zlib[=file]       compile libzlib using the default distribution or the provided file"
   echo "  --without-zlib           skip compiling libzlib"
   echo "  --with-flex[=file]       compile flex using the default distribution or the provided file"
   echo "  --without-flex           skip compiling flex; flex must be installed on the system"
   echo "  --with-hwloc[=file]      compile libhwloc using the default distribution or the provided file"
   echo "  --without-hwloc          skip compiling libhwloc"
   echo "  --with-libevent[=file]   compile libevent using the default distribution or the provided file"
   echo "  --without-libevent       skip compiling libevent"
   echo "  --with-pmix[=file]       compile libpmix using the default distribution or the provided file"
   echo "  --without-pmix           skip compiling libpmix"
   echo "  --with-prrte[=file]      compile libprrte using the default distribution or the provided file"
   echo "  --without-prrte          skip compiling libprrte"
   echo "  --with-openmpi[=file]    compile OpenMPI and related libraries using the default distribution or the provided file"
   echo "  --without-openmpi        skip compiling OpenMPI and related libraries; MPI plus development libraries must be installed on the system"
   echo "  --with-mpich[=file]      compile MPICH and related libraries using the default distribution or the provided file"
   echo "  --without-mpich          skip compiling MPICH and related libraries; MPI plus development libraries must be installed on the system"
   echo "  --with-hypre[=file]      compile libHYPRE using the default distribution or the provided file"
   echo "  --without-hypre          skip compiling libHYPRE"
   echo "  --with-cmake[=file]      compile cmake during petsc compilation"
   echo "  --without-cmake          skip compiling cmake: cmake must be installed on the system"
   echo "  --with-petsc[=file]      compile PETSc and related libraries using the default distribution or the provided file"
   echo "  --without-petsc          skip compiling PETSc and related libraries"
   echo "  --with-mfem[=file]       compile libmfem using the default distribution or the provided file"
   echo "  --without-mfem           skip compiling libmfem"
   echo "  --with-OpenParEM         compile OpenParEM"
   echo "  --without-OpenParEM      skip compiling OpenParEM"
   echo "  --with-OpenParEMg        compile OpenParEMg"
   echo "  --without-OpenParEMg     skip compiling OpenParEMg"
   echo ""
   echo "developer OPTIONS:"
   echo "  --precompiled-bin        compile for a portable pre-compiled binary using a locally compiled version of gcc; forces --clean-in-place"
   exit $retval
fi

echo "#------------------------------------------------------------------------------------"
echo "# OpenParEM_build: setup"
echo "#------------------------------------------------------------------------------------"

export PATH="$install_path/bin:$scripts_dir:$PATH"
export LD_LIBRARY_PATH=$install_path/lib:$install_path/lib64:$install_path/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

echo "scripts_dir=$scripts_dir"
echo "install_path=$install_path"
echo "PATH=$PATH"
echo "jobs=$jobs"

# override openmpi
if [ "$with_openmpi" = "1" ] && [ "$with_mpich" = "1" ]; then
   echo "Overriding OpenMPI with MPICH"
   with_openmpi=0
fi

# do not compile things that are only needed by openmpi
if [ "$with_mpich" = "1" ]; then
   with_m4=0
   with_zlib=0
   with_hwloc=0
   with_libevent=0
   with_pmix=0
   with_prrte=0
fi

# GUI options

#if [ "$with_gui" = "1" ]; then
#   with_freetype=1
#   with_tcl=1
#   with_tk=1
#   with_occt=1
#   with_gmsh=1
#   with_qt=1
#fi

#if [ "$with_gui" = "0" ]; then
#   with_freetype=0
#   with_tcl=0
#   with_tk=0
#   with_occt=0
#   with_gmsh=0
#   with_qt=0
#fi

# show the setup

   if [ "$with_meson" = "1" ]; then
      echo "with-meson=$with_meson using $meson"
   else
      echo "with-meson=$with_meson"
   fi

   if [ "$with_xcb" = "1" ]; then
      echo "with-xcb=$with_xcb using $xcb"
   else
      echo "with-xcb=$with_xcb"
   fi

   if [ "$with_freetype" = "1" ]; then
      echo "with-freetype=$with_freetype using $freetype"
   else
      echo "with-freetype=$with_freetype"
   fi

   if [ "$with_tcl" = "1" ]; then
      echo "with-tcl=$with_tcl using $tcl"
   else
      echo "with-tcl=$with_tcl"
   fi

   if [ "$with_tk" = "1" ]; then
      echo "with-tk=$with_tk using $tk"
   else
      echo "with-tk=$with_tk"
   fi

   if [ "$with_occt" = "1" ]; then
      echo "with-occt=$with_occt using $occt"
   else
      echo "with-occt=$with_occt"
   fi

   if [ "$with_gmsh" = "1" ]; then
      echo "with-gmsh=$with_gmsh using $gmsh"
   else
      echo "with-gmsh=$with_gmsh"
   fi

   if [ "$with_qt" = "1" ]; then
      echo "with-qt=$with_qt using $qt"
   else
      echo "with-qt=$with_qt"
   fi

   if [ "$with_m4" = "1" ]; then
      echo "with-m4=$with_m4 using $m4"
   else
      echo "with-m4=$with_m4"
   fi

   if [ "$with_bison" = "1" ]; then
      echo "with-bison=$with_bison using $bison"
   else
      echo "with-bison=$with_bison"
   fi

   if [ "$with_zlib" = "1" ]; then
      echo "with-zlib=$with_zlib using $zlib"
   else
      echo "with-zlib=$with_zlib"
   fi

   if [ "$with_flex" = "1" ]; then
      echo "with-flex=$with_flex using $flex"
   else
      echo "with-flex=$with_flex"
   fi

   if [ "$with_hwloc" = "1" ]; then
      echo "with-hwloc=$with_hwloc using $hwloc"
   else
      echo "with-hwloc=$with_hwloc"
   fi

   if [ "$with_libevent" = "1" ]; then
      echo "with-libevent=$with_libevent using $libevent"
   else
      echo "with-libevent=$with_libevent"
   fi

   if [ "$with_pmix" = "1" ]; then
      echo "with-pmix=$with_pmix using $pmix"
   else
      echo "with-pmix=$with_pmix"
   fi

   if [ "$with_prrte" = "1" ]; then
      echo "with-prrte=$with_prrte using $prrte"
   else
      echo "with-prrte=$with_prrte"
   fi

   if [ "$with_openmpi" = "1" ]; then
      echo "with-openmpi=$with_openmpi using $openmpi"
   else
      echo "with-openmpi=$with_openmpi"
   fi

   if [ "$with_mpich" = "1" ]; then
      echo "with-mpich=$with_mpich using $mpich"
   else
      echo "with-mpich=$with_mpich"
   fi

   if [ "$with_hypre" = "1" ]; then
      echo "with-hypre=$with_hypre using $hypre"
   else
      echo "with-hypre=$with_hypre"
   fi

   if [ "$with_petsc" = "1" ]; then
      echo "with-petsc=$with_petsc using $petsc"
      echo "   including:"
      echo "      fblaslapack=$fblaslapack"
      echo "      mumps=$mumps"
      echo "      scalapack=$scalapack"
      echo "      scotch=$scotch"

      if [ "$with_cmake" = "1" ]; then
         echo "   with-cmake=$with_cmake using $cmake"
      else
         echo "   with-cmake=$with_cmake"
      fi
   else
      echo "with-petsc=$with_petsc"
   fi

   if [ "$with_mfem" = "1" ]; then
      echo "with-mfem=$with_mfem using $mfem"
   else
      echo "with-mfem=$with_mfem"
   fi

   echo "with-OpenParEM=$with_OpenParEM"

   echo "with-OpenParEMg=$with_OpenParEMg"

if [ "$show_setup" = "1" ]; then
   exit 0
fi

#----------------------------------------------------
# copy Python scripts for FreeCAD and ParaView
#----------------------------------------------------

echo "#------------------------------------------------------------------------------------"
echo "# OpenParEM_build: copying FreeCAD and ParaView scripts"
echo "#------------------------------------------------------------------------------------"

# FreeCAD

cd $HOME
if [ ! -d ".FreeCAD" ]; then
   mkdir ".FreeCAD"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: failed to create $HOME/.FreeCAD directory"
      exit 1
   fi
fi

cd ".FreeCAD"

if [ ! -d "Macro" ]; then
   mkdir "Macro"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: failed to create $HOME/.FreeCAD/Macro directory"
      exit 1
   fi
fi

cd "$scripts_dir"/FreeCAD
if [ $? -ne 0 ]; then
   echo "OpenParEM_ERROR: failed to cd to $scripts_dir/FreeCAD"
   exit 1
fi

echo "copy FreeCAD/OpenParEM2D_save.py to $HOME/.FreeCAD/Macro"
cp OpenParEM2D_save.py "$HOME/.FreeCAD/Macro"

echo "copy FreeCAD/OpenParEM3D_save.py to $HOME/.FreeCAD/Macro"
cp OpenParEM3D_save.py "$HOME/.FreeCAD/Macro"

# ParaView

cd $HOME
if [ ! -d ".config" ]; then
   mkdir ".config"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: failed to create $HOME/.config directory"
      exit 1
   fi
fi

cd ".config"

if [ ! -d "ParaView" ]; then
   mkdir "ParaView"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: failed to create $HOME/.config/ParaView directory"
      exit 1
   fi
fi

cd "ParaView"

if [ ! -d "Macros" ]; then
   mkdir "Macros"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: failed to create $HOME/.config/ParaView/Macros directory"
      exit 1
   fi
fi

cd "$scripts_dir"/ParaView
if [ $? -ne 0 ]; then
   echo "OpenParEM_ERROR: failed to cd to $scripts_dir/ParaView"
   exit 1
fi

echo "copy ParaView/field_plot.py to $HOME/.config/ParaView/Macros"
cp field_plot.py "$HOME/.config/ParaView/Macros"

cd "$scripts_dir"

#----------------------------------------------------
# clean in place
#----------------------------------------------------

if [ "$clean_in_place" = "1" ]; then
   cd ..
   echo "rm -Rf bin etc include lib lib64 libexec local man sbin share metatypes mkspecs modules phrasebooks plugins qml sbom translations var"
   rm -Rf bin etc include lib lib64 libexec local man sbin share metatypes mkspecs modules phrasebooks plugins qml sbom translations var
   cd "$scripts_dir"
fi

echo "#----------------------------------------------------"
echo "# download packages and verify"
echo "#----------------------------------------------------"

m4="m4-1.4.19.tar.gz"
download_package_and_verify_sig "$m4" "https://ftp.gnu.org/gnu/m4/$m4" "sig" "$GNU_KEYRING" "" || exit 1

bison="bison-3.8.tar.gz"
download_package_and_verify_sig "$bison" "https://ftp.gnu.org/gnu/bison/$bison" "sig" "$GNU_KEYRING" "" || exit 1

zlib="zlib-1.3.1.tar.gz"
download_package_and_verify_sig "$zlib" "https://github.com/madler/zlib/releases/download/v1.3.1/$zlib" "asc" "$MADLER_KEYRING" "" || exit 1

flex="flex-2.6.4.tar.gz"
flex_sha256="e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995"
download_package_and_verify_sha256 "$flex" "https://github.com/westes/flex/releases/download/v2.6.4/$flex" "$flex_sha256" || exit 1

hwloc="hwloc-2.13.0.tar.gz"
hwloc_sha256="1514a5253f0a5c23bc006d3bdd30a6f6125c9a8dc9b5fa4984913d1fff45315d"
download_package_and_verify_sha256 "$hwloc" "https://www.open-mpi.org/software/hwloc/v2.13/downloads/$hwloc" "$hwloc_sha256" || exit 1

libevent="libevent-2.1.13-stable.tar.gz"
libevent_sha256="f7e9383b8c0baa81b687e5b5eecc01beefaf1b19b64151d95ed61647fe7a315c"
download_package_and_verify_sha256 "$libevent" "https://github.com/libevent/libevent/releases/download/release-2.1.13-stable/$libevent" "$libevent_sha256" || exit 1

pmix="pmix-5.0.11.tar.gz"
pmix_sha="a46605489e6f24865bb61efaf02b6730bc9f5e00"
download_package_and_verify_sha "$pmix" "https://github.com/openpmix/openpmix/releases/download/v5.0.11/$pmix" "$pmix_sha" || exit 1

prrte="prrte-3.0.14.tar.gz"
prrte_sha="b31c81822ded11d8fb7d339ccc40042f21ef29d7"
download_package_and_verify_sha "$prrte" "https://github.com/openpmix/prrte/releases/download/v3.0.14/$prrte" "$prrte_sha" || exit 1

openmpi="openmpi-4.1.8.tar.gz"
openmpi_sha256="fb41086bbed9300baa2f3d7572491facfe5257412fa524ec5a396aa9101d5c62"
download_package_and_verify_sha256 "$openmpi" "https://download.open-mpi.org/release/open-mpi/v4.1/$openmpi" "$openmpi_sha256" || exit 1

mpich="mpich-4.3.2.tar.gz"
# self-generated sha256 from a 3-3-2026 download
mpich_sha256="47d774587a7156a53752218c811c852e70ac44db9c502dc3f399b4cb817e3818"
download_package_and_verify_sha256 "$mpich" "https://www.mpich.org/static/downloads/4.3.2/$mpich" "$mpich_sha256" || exit 1

hypre_root="3.1.0.tar.gz"
hypre="hypre-$hypre_root"
# self-generated from 8-19-2026 download
hypre_sha256="a6879ae9375d95c26afd97141d61e7a8092807333bf40cd180b385aed7351b2d"
download_package_and_verify_sha256 "$hypre" "https://github.com/hypre-space/hypre/archive/refs/tags/v$hypre_root" "$hypre_sha256" || exit 1
if [ -f "$hypre_root" ]; then
   mv ../$DOWNLOAD_DIR/$hypre_root ./$DOWNLOAD_DIR/$hypre
fi

petsc="petsc-3.25.4.tar.gz"
# self-generated from 8-19-2026 download
petsc_sha256="12c990fb39a5764ac8311211d09c01ed80fb983136c75bf7b558312b2509dbbd"
download_package_and_verify_sha256 "$petsc" "https://web.cels.anl.gov/projects/petsc/download/release-snapshots/$petsc" "$petsc_sha256" || exit 1

mfem_root="4.9.tar.gz"
mfem="mfem-$mfem_root"
# self-generated from 8-19-2026 download
mfem_sha256="ea3ac13e182c09f05b414b03a9bef7a4da99d45d67ee409112b8f11058447a7c"
download_package_and_verify_sha256 "$mfem" "https://github.com/mfem/mfem/archive/refs/tags/v$mfem_root" "$mfem_sha256" || exit 1
if [ -f "$mfem_root" ]; then
   mv ../$DOWNLOAD_DIR/$mfem_root ./$DOWNLOAD_DIR/$mfem
fi

libXau="libXau-1.0.12.tar.gz"
download_package_and_verify_sig "$libXau" "https://www.x.org/archive/individual/lib/$libXau" "sig" "$ACOOPERSMITH_KEYRING" "" || exit 1

libXdmcp="libXdmcp-1.1.5.tar.gz"
download_package_and_verify_sig "$libXdmcp" "https://www.x.org/archive/individual/lib/$libXdmcp" "sig" "$ACOOPERSMITH_KEYRING" "" || exit 1

ninja_root="1.13.2.tar.gz"
ninja="ninja-$ninja_root"
# self-generated from 8-20-2026 download
ninja_sha256="974d6b2f4eeefa25625d34da3cb36bdcebe7fbce40f4c16ac0835fd1c0cbae17"
download_package_and_verify_sha256 "$ninja" "https://github.com/ninja-build/ninja/archive/refs/tags/v$ninja_root" "$ninja_sha256" || exit 1
if [ -f "$ninja_root" ]; then
   mv ../$DOWNLOAD_DIR/$ninja_root ./$DOWNLOAD_DIR/$ninja
fi

meson="meson-1.12.0.tar.gz"
meson_sha256="88afe0c20e52030218924ac37d0c81c59b4b5f3ae3752c8c6d7470c7d365886c"
download_package_and_verify_sha256 "$meson" "https://github.com/mesonbuild/meson/releases/download/1.12.0/$meson" "$meson_sha256" || exit 1

xcb_proto="xcb-proto-1.17.0.tar.gz"
download_package_and_verify_sig "$xcb_proto" "https://xorg.freedesktop.org/archive/individual/proto/$xcb_proto" "sig" "$MTURNER_KEYRING" "" || exit 1

libxcb="libxcb-1.17.0.tar.gz"
download_package_and_verify_sig "$libxcb" "https://www.x.org/archive/individual/lib/$libxcb" "sig" "$MTURNER_KEYRING" "" || exit 1

xcb_util="xcb-util-0.4.1.tar.gz"
download_package_and_verify_sig "$xcb_util" "https://xcb.freedesktop.org/dist/$xcb_util" "sig" "$ACOOPERSMITH_KEYRING" "" || exit 1

xcb_util_image=xcb-util-image-0.4.1.tar.gz
download_package_and_verify_sig "$xcb_util_image" "https://xcb.freedesktop.org/dist/$xcb_util_image" "sig" "$ACOOPERSMITH_KEYRING" "" || exit 1

xcb_util_keysims="xcb-util-keysyms-0.4.1.tar.gz"
download_package_and_verify_sig "$xcb_util_keysims" "https://xcb.freedesktop.org/dist/$xcb_util_keysims" "sig" "$ACOOPERSMITH_KEYRING" "" || exit 1

xcb_util_renderutil="xcb-util-renderutil-0.3.10.tar.gz"
download_package_and_verify_sig "$xcb_util_renderutil" "https://xcb.freedesktop.org/dist/$xcb_util_renderutil" "sig" "$ACOOPERSMITH_KEYRING" "" || exit 1

xcb_util_wm="xcb-util-wm-0.4.2.tar.gz"
download_package_and_verify_sig "$xcb_util_wm" "https://xcb.freedesktop.org/dist/$xcb_util_wm" "sig" "$ACOOPERSMITH_KEYRING" "" || exit 1

xcb_util_cursor="xcb-util-cursor-0.1.6.tar.gz"
download_package_and_verify_sig "$xcb_util_cursor" "https://xcb.freedesktop.org/dist/$xcb_util_cursor" "sig" "$ACOOPERSMITH2_KEYRING" "" || exit 1

xcb_util_errors="xcb-util-errors-1.0.1.tar.gz"
download_package_and_verify_sig "$xcb_util_errors" "https://xcb.freedesktop.org/dist/$xcb_util_errors" "sig" "$ACOOPERSMITH_KEYRING" "" || exit 1

libxml2="libxml2-v2.15.3.tar.gz"
# self-generated from 8-20-2026 download
libxml2_sha256="0da50c1415f4ec0364569d2119b1436ba837b31df44af28569d234272c23cf1f"
download_package_and_verify_sha256 "$libxml2" "https://gitlab.gnome.org/GNOME/libxml2/-/archive/v2.15.3/$libxml2" "$libxml2_sha256" || exit 1

xkbcommon="xkbcommon-1.13.2.tar.gz"
# self-generated from 8-20-2026 download
xkbcommon_sha256="acc4d5f7c3cbba5f9f8d08d8bdbeede84ecede46792f47929aa9321873385528"
download_package_and_verify_sha256 "$xkbcommon" "https://github.com/xkbcommon/libxkbcommon/archive/refs/tags/$xkbcommon" "$xkbcommon_sha256" || exit 1
cd ../external_packages
tar -xf xkbcommon-1.13.2.tar.gz
tar -cf libxkbcommon-xkbcommon-1.13.2.tar.gz libxkbcommon-xkbcommon-1.13.2
gzip libxkbcommon-xkbcommon-1.13.2.tar.gz
xkbcommon="libxkbcommon-xkbcommon-1.13.2.tar.gz"
cd ../scripts

libX11="libX11-1.8.tar.gz"
download_package_and_verify_sig "$libX11" "https://www.x.org/archive/individual/lib/$libX11" "sig" "$AJACKSON_KEYRING" "" || exit 1

freetype="freetype-2.14.3.tar.gz"
download_package_and_verify_sig "$freetype" "https://sourceforge.net/projects/freetype/files/freetype2/2.14.3/$freetype" "sig" "$WLEMBERG_KEYRING" "/download" || exit 1

tcl="tcl8.6.16-src.tar.gz"
# self-generated from 8-19-2026 download
tcl_sha256="91cb8fa61771c63c262efb553059b7c7ad6757afa5857af6265e4b0bdc2a14a5"
download_package_and_verify_sha256 "$tcl" "http://prdownloads.sourceforge.net/tcl/$tcl" "$tcl_sha256" || exit 1

tk="tk8.6.16-src.tar.gz"
# self-generated from 8-19-2026 download
tk_sha256="be9f94d3575d4b3099d84bc3c10de8994df2d7aa405208173c709cc404a7e5fe"
download_package_and_verify_sha256 "$tk" "http://prdownloads.sourceforge.net/tcl/$tk" "$tk_sha256" || exit 1

occt_root="7_9_3.tar.gz"
occt="OCCT-$occt_root"
# self-generated from 8-19-2026 download
occt_sha256="5ecf094ec6b12d5413dfb851d8c3590c354058aee556e32e408bdfbf8c357d57"
download_package_and_verify_sha256 "$occt" "https://github.com/Open-Cascade-SAS/OCCT/archive/refs/tags/V$occt_root" "$occt_sha256" || exit 1
if [ -f "$occt_root" ]; then
   mv ../$DOWNLOAD_DIR/$occt_root ./$DOWNLOAD_DIR/$occt
fi

gmsh="gmsh-4.15.2-source.tgz"
# self-generated from 8-19-2026 download
gmsh_sha256="be3f66f225d27ba9fa014f07e83169285da8a051b0e8ab7103d88066b39bdd3e"
download_package_and_verify_sha256 "$gmsh" "https://gmsh.info/src/$gmsh" "$gmsh_sha256" || exit 1

dbus1="dbus-1.16.2.tar.xz"
download_package_and_verify_sig "$dbus1" "https://dbus.freedesktop.org/releases/dbus/$dbus1" "asc" "$SMCVITTIE_KEYRING" "" || exit 1

icu4c="icu4c-78.3-sources.tgz"
download_package_and_verify_sig "$icu4c" "https://github.com/unicode-org/icu/releases/download/release-78.3/$icu4c" "asc" "$ICUROBOT_KEYRING" "" || exit 1
cd ../external_packages
if [ -f icu.tar.gz ]; then
   rm icu.tar.gz
fi
tar -xf icu4c-78.3-sources.tgz
tar -cf icu.tar icu
gzip icu.tar
icu4c="icu.tar.gz"
cd ../scripts

qt="qt-everywhere-src-6.11.2.tar.xz"
qt_sha256="6dcfbca271d76a6502741a2c0dc6fc98ef7dd0b7b4cfd0abcebb285a86a26f33"
download_package_and_verify_sha256 "$qt" "https://download.qt.io/official_releases/qt/6.11/6.11.2/single/$qt" "$qt_sha256" || exit 1

#----------------------------------------------------
# check for installed build tools
#----------------------------------------------------

has_build=0

if [ "$with_meson" = "1" ]; then
   has_build=1
fi

if [ "$with_xcb" = "1" ]; then
   has_build=1
fi

if [ "$with_freetype" = "1" ]; then
   has_build=1
fi

if [ "$with_tcl" = "1" ]; then
   has_build=1
fi

if [ "$with_tk" = "1" ]; then
   has_build=1
fi

if [ "$with_occt" = "1" ]; then
   has_build=1
fi

if [ "$with_gmsh" = "1" ]; then
   has_build=1
fi

if [ "$with_qt" = "1" ]; then
   has_build=1
fi

if [ "$with_m4" = "1" ]; then
   has_build=1
fi

if [ "$with_bison" = "1" ]; then
   has_build=1
fi

if [ "$with_zlib" = "1" ]; then
   has_build=1
fi

if [ "$with_flex" = "1" ]; then
   has_build=1
fi

if [ "$with_hwloc" = "1" ]; then
   has_build=1
fi

if [ "$with_libevent" = "1" ]; then
   has_build=1
fi

if [ "$with_pmix" = "1" ]; then
   has_build=1
fi

if [ "$with_prrte" = "1" ]; then
   has_build=1
fi

if [ "$with_openmpi" = "1" ]; then
   has_build=1
fi

if [ "$with_mpich" = "1" ]; then
   has_build=1
fi

if [ "$with_hypre" = "1" ]; then
   has_build=1
fi

if [ "$with_petsc" = "1" ]; then
   has_build=1
fi

if [ "$with_mfem" = "1" ]; then
   has_build=1
fi

if [ "$with_OpenParEM" = "1" ]; then
   has_build=1
fi

if [ "$with_OpenParEMg" = "1" ]; then
   has_build=1
fi

if [ "$has_build" = "0" ]; then
   exit 0
fi


missing_requirement=0

which make > /dev/null 2>&1
if [ $? -ne 0 ]; then
   echo "ERROR: \"make\" must be installed on the system to compile OpenParEM"
   missing_requirement=1
fi

which g++ > /dev/null 2>&1
if [ $? -ne 0 ]; then
   echo "ERROR: \"g++\" must be installed on the system to compile OpenParEM"
   missing_requirement=1
fi

which gfortran > /dev/null 2>&1
if [ $? -ne 0 ]; then
   echo "ERROR: \"gfortran\" must be installed on the system to compile OpenParEM"
   missing_requirement=1
fi

which perl > /dev/null 2>&1
if [ $? -ne 0 ]; then
   echo "ERROR: \"perl\" must be installed on the system to compile OpenParEM"
   missing_requirement=1
fi

if [ "$missing_requirement" = "1" ]; then
   exit 1
fi

#----------------------------------------------------
# builds
#----------------------------------------------------

echo "#------------------------------------------------------------------------------------"
echo "# OpenParEM_build: build prep (if any)"
echo "#------------------------------------------------------------------------------------"

cd ..

if [ "$precompiled_bin" = "1" ]; then
   echo "using local gcc build $gcc_version"

   cd ../"$gcc_version"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: failed to change to local gcc installation"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: failed to install the local gcc installation"
      exit 1
   fi

   # Note that libc and libm are part of the operating system installation.  If the versions
   # on the target system are too old, then a run-time error will occur.

   cd ../OpenParEM
fi

# m4
if [ "$with_m4" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: m4"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$m4"

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: m4 failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: m4 failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: m4 failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..
fi

# bison
if [ "$with_bison" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: bison"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$bison"

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: bison failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: bison failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: bison failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..
fi


# meson and ninja
if [ "$with_meson" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: ninja"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $ninja

   ./configure.py --bootstrap
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: ninja failed to build"
      exit 1
   fi

   cp ninja "$install_path/bin"

   cd ..
   remove_base_directory
   cd ..

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: meson"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $meson

   python3 packaging/create_zipapp.py --outfile="$install_path/bin/meson" --interpreter='/usr/bin/env python3'

   chmod +x "$install_path/bin/meson"

   cd ..
   remove_base_directory
   cd ..



fi

# xcb
if [ "$with_xcb" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: xcb and dependencies"
   echo "#------------------------------------------------------------------------------------"

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: libXau"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $libXau
   package_name=libXau

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: libXdmcp"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $libXdmcp
   package_name=libXdmcp

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: xcb_proto"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $xcb_proto
   package_name=xcb_proto

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: libxcb"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $libxcb
   package_name=libxcb

   PKG_CONFIG_PATH="$install_path/share/pkgconfig" ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: xcb_util"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $xcb_util
   package_name=xcb_util

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: xcb_util_image"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $xcb_util_image
   package_name=xcb_util_image

   PKG_CONFIG_PATH="$install_path/lib/pkgconfig" ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: xcb_util_keysims"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $xcb_util_keysims
   package_name=xcb_util_keysims

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: xcb_util_renderutil"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $xcb_util_renderutil
   package_name=xcb_util_renderutil

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: xcb_util_wm"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $xcb_util_wm
   package_name=xcb_util_wm

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: xcb_util_cursor"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $xcb_util_cursor
   package_name=xcb_util_cursor

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: xcb_util_errors"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $xcb_util_errors
   package_name=xcb_util_errors

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..


   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: libxml2"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $libxml2
   package_name=libxml2

   mkdir build
   cd build

   cmake .. \
    -DCMAKE_INSTALL_PREFIX="$install_path" \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=OFF

   cmake --build . -j "$jobs"
   cmake --install .

   cd ../..
   remove_base_directory
   cd ..

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: xkbcommon"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $xkbcommon
   package_name=xkbcommon

   meson setup build --prefix="$install_path" -Denable-wayland=false -Denable-bash-completion=false
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: xkbcommon failed to setup build"
      exit 1
   fi

   meson compile -C build
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: xkbcommon failed to compile"
      exit 1
   fi


   #meson test -C build 
   #if [ $? -ne 0 ]; then
   #   echo "OpenParEM_ERROR: xkbcommon failed to test"
   #   exit 1
   #fi

   cd build
   meson install
   cd ..

   cd ..

   remove_base_directory
   cd ..

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: libX11"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $libX11
   package_name=libX11

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: $package_name failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..


fi


# freetype
if [ "$with_freetype" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: freetype"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$freetype"

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: freetype failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: freetype failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: freetype failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..
fi

# tcl
if [ "$with_tcl" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: tcl"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$tcl"
 
   cd unix

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: tcl failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: tcl failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: tcl failed to install"
      exit 1
   fi


   cd ../..
   remove_base_directory
   cd ..

   # put a soft link to the versioned tclsh

   current_dir=$PWD

   if [ ! -d $install_path/bin ]; then
      echo "OpenParEM_ERROR: tcl failed to find install directory"
      exit 1
   fi

   cd $install_path/bin

   if [ -f tclsh ]; then
      rm tclsh
   fi

   tclsh=`ls tcl*`
   if [ ! -f "$tclsh" ]; then
      echo "OpenParEM_ERROR: tcl failed to find tclsh"
      exit 1
   fi

   ln -s $tclsh tclsh
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: tcl failed to softlink tclsh"
      exit 1
   fi

   cd $current_dir
fi

# tk
if [ "$with_tk" = "1" ]; then 

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: tk"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$tk"

   cd unix

   ./configure CPPFLAGS="-I$install_path/include" --prefix="$install_path" --with-tcl=$install_path/lib
   if [ $? -ne 0 ]; then 
      echo "OpenParEM_ERROR: tk failed to configure"
      exit 1  
   fi

   make -j "$jobs" 
   if [ $? -ne 0 ]; then 
      echo "OpenParEM_ERROR: tk failed to make"
      exit 1  
   fi

   make install 
   if [ $? -ne 0 ]; then 
      echo "OpenParEM_ERROR: tk failed to install"
      exit 1  
   fi

   cd ../.. 
   remove_base_directory
   cd .. 

   # put a soft link to the versioned wish

   current_dir=$PWD

   if [ ! -d $install_path/bin ]; then
      echo "OpenParEM_ERROR: tk failed to find install directory"
      exit 1
   fi

   cd $install_path/bin

   if [ -f wish ]; then
      rm wish
   fi

   wish=`ls wish*`
   if [ ! -f "$wish" ]; then
      echo "OpenParEM_ERROR: tk failed to find wish"
      exit 1
   fi

   ln -s $wish wish
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: tk failed to softlink wish"
      exit 1
   fi

   cd $current_dir
  
fi

# zlib
if [ "$with_zlib" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: zlib"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$zlib"

   if [ "$enable_static" = "yes" ]; then 
      ./configure --static --prefix="$install_path"
      if [ $? -ne 0 ]; then
         echo "OpenParEM_ERROR: zlib failed to configure"
         exit 1
      fi
   else
      ./configure --prefix="$install_path"
      if [ $? -ne 0 ]; then
         echo "OpenParEM_ERROR: zlib failed to configure"
         exit 1
      fi
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: zlib failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: zlib failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..
fi

# flex
if [ "$with_flex" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: flex"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$flex"

   ./configure --prefix="$install_path" --enable-static="$enable_static" --enable-shared="$enable_shared"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: flex failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: flex failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: flex failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..
fi

# hwloc
if [ "$with_hwloc" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: hwloc"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$hwloc"

   ./configure --prefix="$install_path" --enable-static="$enable_static" --enable-shared="$enable_shared"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: hwloc failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: hwloc failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: hwloc failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..
fi

# libevent
if [ "$with_libevent" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: libevent"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$libevent"

   ./configure --prefix="$install_path" --enable-static="$enable_static" --enable-shared="$enable_shared" --disable-openssl
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: libevent failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: libevent failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: libevent failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..
fi

# pmix
if [ "$with_pmix" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: pmix"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$pmix"

   ./configure CFLAGS=-fPIC --prefix="$install_path" --enable-static="$enable_static" --enable-shared="$enable_shared" --with-libevent="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: pmix failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: pmix failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: pmix failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..
fi

# prrte
if [ "$with_prrte" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: prrte"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$prrte"

   ./configure --prefix="$install_path" --enable-static="$enable_static" --enable-shared="$enable_shared" --with-pmix="$install_path" --with-libevent="$install_path" --with-hwloc="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: prrte failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: prrte failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: prrte failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..
fi

# openmpi
if [ "$with_openmpi" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: openmpi"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$openmpi"

   ./configure --prefix="$install_path" --enable-static="$enable_static" --enable-shared="$enable_shared" --with-libevent="$install_path" --with-hwloc="$install_path" --with-pmix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: openmpi failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: openmpi failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: openmpi failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..

fi

# mpich
if [ "$with_mpich" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: mpich"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$mpich"

   # The device has a large impact on performance that is hardware dependent.  Experimentation is in order.

   # configure selects the device
   # extremely slow in eigenvalue solve when excessive slots are specified
   # <10% slower than with ch3:nemesis on normal run
   #./configure --prefix="$install_path" --enable-static="$enable_static" --enable-shared="$enable_shared" 

   # good on the eigenvalue solve when excessive slots are speccified
   # but 50% slower on small cases
   #./configure --prefix="$install_path" --enable-static="$enable_static" --enable-shared="$enable_shared" --with-device=ch3:sock

   # extremely slow in eigenvalue solve when excessive slots are specified
   #./configure --prefix="$install_path" --enable-static="$enable_static" --enable-shared="$enable_shared" --with-device=ch3:nemesis

   # not supported
   #./configure --prefix="$install_path" --enable-static="$enable_static" --enable-shared="$enable_shared" --with-device=ch4:nemsis

   # extremely slow in eigenvalue solve when excessive slots are specified
   # faster than OpenMPI for a small case
   ./configure --prefix="$install_path" --enable-static="$enable_static" --enable-shared="$enable_shared" --with-device=ch4:ucx

   # extremely slow in eigenvalue solve when excessive slots are specified
   # <10% slower than OpenMPI for a small case
   #./configure --prefix="$install_path" --enable-static="$enable_static" --enable-shared="$enable_shared" --with-device=ch4:ofi


   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: mpich failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: mpich failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: mpich failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..

fi

# hypre
if [ "$with_hypre" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: hypre"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$hypre"

   cd src

   ./configure --prefix="$install_path" --enable-shared="$enable_shared"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: hypre failed to configure"
      exit 1
   fi

   make -j "$jobs" install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: hypre failed to make and install"
      exit 1
   fi

   cd ../..
   remove_base_directory
   cd ..
fi

# petsc
if [ "$with_petsc" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: petsc"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$petsc"

   if [ -d linux_complex ]; then
      rm -Rf linux_complex
      if [ $? -ne 0 ]; then
         echo "OpenParEM_ERROR: petsc failed to remove linux_complex"
         exit 1
      fi
   fi

   cmake_option="no"
   if [ "$with_cmake" = "1" ]; then
      cmake_option="$cmake"
   fi

#   mkdir temp_dir
#   --with-packages-download-dir=temp_dir

   ./configure --prefix="$install_path" PETSC_ARCH=linux_complex --with-clean --with-shared-libraries="$enable_shared" --with-debugging=0 --with-single-library=0 --with-scalar-type=complex --with-precision=double --with-64-bit-indices --download-cmake="$cmake_option" --download-zlib=no --download-openmpi=no --download-bison=no --download-hypre=no --download-metis="$metis" --download-slepc=yes --download-mfem=no --download-mumps="$mumps" --download-scalapack="$scalapack" --download-ptscotch="$scotch" --download-fblaslapack="$fblaslapack" --with-fortran-bindings=1 --COPTFLAGS="-O3" --CXXOPTFLAGS="-O3" --FOPTFLAGS="-O3"


   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: petsc failed to configure"
      exit 1
   fi

   make -j "$jobs" PETSC_DIR="$PWD" PETSC_ARCH=linux_complex all
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: petsc failed to make"
      exit 1
   fi

   make PETSC_DIR="$PWD" PETSC_ARCH=linux_complex install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: petsc failed to install"
      exit 1
   fi

   make PETSC_DIR="$install_path" PETSC_ARCH="" check
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: petsc failed check"
      exit 1
   fi

   make SLEPC_DIR="$install_path" PETSC_DIR="$install_path" PETSC_ARCH="" check
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: slepc failed check"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..
fi

# mfem
if [ "$with_mfem" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: mfem"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$mfem"

   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: mfem failed to configure"
      exit 1
   fi

   ENABLE_STATIC=NO
   if [ "$enable_static" = "yes" ]; then
      ENABLE_STATIC=YES
   fi

   ENABLE_SHARED=NO
   if [ "$enable_shared" = "yes" ]; then
      ENABLE_SHARED=YES
   fi

   make parallel -j "$jobs" MFEM_USE_METIS_5=YES MFEM_USE_EXCEPTIONS=YES HYPRE_DIR=$install_path SHARED=$ENABLE_SHARED STATIC=$ENABLE_STATIC
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: mfem failed to make"
      exit 1
   fi

   make PREFIX="$install_path" install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: mfem failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..

   # comment out some lines that cause compiling issues when using OCCT
   current_dir=$PWD
   if [ -f $install_path/include/mfem/linalg/linalg.hpp ]; then
      cd $install_path/include/mfem/linalg
      sed -i 's$#include "batched/batched.hpp"$//#include "batched/batched.hpp"$' linalg.hpp
      sed -i 's$#include "batched/gpu_blas.hpp"$//#include "batched/gpu_blas.hpp"$' linalg.hpp
      sed -i 's$#include "batched/solver.hpp"$//#include "batched/solver.hpp"$' linalg.hpp
      cd $current_dir
   else
      echo "OpenParEM_ERROR: mfem failed include file edit"
      exit 1
   fi

fi

# occt
if [ "$with_occt" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: occt"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$occt"

   cmake -D INSTALL_SAMPLES=ON -D 3RDPARTY_DIR:PATH="$install_path" -D 3RDPARTY_FREETYPE_DIR:PATH="$install_path" -D 3RDPARTY_TCL_DIR:PATH="$install_path" -D 3RDPARTY_TK_DIR:PATH="$install_path" -D 3RDPARTY_TK_LIBRARY_DIR:FILEPATH="$install_path/lib" -D INSTALL_DIR:PATH="$install_path" .

   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: occt failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: occt failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: occt failed to install"
      exit 1
   fi

   cd ..
   remove_base_directory
   cd ..
fi

# gmsh
if [ "$with_gmsh" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: gmsh"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$gmsh"

   mkdir build
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: gmsh failed to create a build directory"
      exit 1
   fi

   cd build

   # EIGEN is enabled; can substitute Blas/Lapack if EIGEN becomes a problem
   cmake -D CMAKE_INSTALL_PREFIX="$install_path" -D ENABLE_BUILD_SHARED=ON -D ENABLE_DOMHEX=OFF -D ENABLE_EIGEN=ON -D ENABLE_FLTK=OFF -D ENABLE_GETDP=OFF -D ENABLE_GMM=OFF -D ENABLE_GMP=OFF -D ENABLE_KBIPACK=OFF -D ENABLE_MED=OFF -D ENABLE_MMG=OFF -D ENABLE_MPEG_ENCODE=OFF -D ENABLE_ONELAB=OFF -D ENABLE_ONELAB_METAMODEL=OFF -D ENABLE_OPENMP=OFF -D ENABLE_OPTHOM=OFF -D ENABLE_PLUGINS=OFF -D ENABLE_POST=OFF -D ENABLE_QUADMESHINGTOOLS=OFF -D ENABLE_QUADTRI=OFF -D ENABLE_SOLVER=OFF -D ENABLE_TOUCHBAR=OFF -D ENABLE_VOROPP=OFF  ..

   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: gmsh failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: gmsh failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: gmsh failed to install"
      exit 1
   fi

   cd ../..
   remove_base_directory
   cd ..
fi


# qt
if [ "$with_qt" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: dbus-1"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $dbus1

   meson setup build --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: dbus-1 failed to setup build"
      exit 1
   fi

   meson compile -C build
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: dbus-1 failed to compile"
      exit 1
   fi


   #meson test -C build
   #if [ $? -ne 0 ]; then
   #   echo "OpenParEM_ERROR: dbus-1 failed to test"
   #   exit 1
   #fi

   cd build
   meson install
   cd ..

   cd ..
   remove_base_directory
   cd ..

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: icu4c"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter $icu4c

   cd source
   chmod +x runConfigureICU configure install-sh

   ./runConfigureICU Linux --prefix="$install_path" --enable-rpath
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: icu4c failed to configure build"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: icu4c failed to build"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: icu4c failed to install"
      exit 1
   fi

   cd ../..
   remove_base_directory
   cd ..


   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: qt"
   echo "#------------------------------------------------------------------------------------"

   cd external_packages

   unpack_and_enter "$qt"

   mkdir build
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: gmsh failed to create a build directory"
      exit 1
   fi

   cd build

   #../configure --prefix="$install_path" --skip qtconnectivity,qtsensors,qtserialport,qtserialbus,qtpositioning,qtlocation,qtwebengine,qtmultimedia,qtwebsockets,qtsql,qtremoteobjects,qtpurchase,qtquick3d,qtquicktimeline,qtsvg,qtquick3dphysics,qtspeech,qtvirtualkeyboard
   ../configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: qt failed to configure"
      exit 1
   fi

   cmake --build . --parallel "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: qt failed to make"
      exit 1
   fi

   cmake --install .
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: qt failed to install"
      exit 1
   fi

   cd ../..
   remove_base_directory
   cd ..
fi


# OpenParEM
if [ "$with_OpenParEM" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: OpenParEM"
   echo "#------------------------------------------------------------------------------------"

   cd src

   make clean
   if [ $? -ne 0 ]; then
      echo "OpenParEM_INFO: OpenParEM failed to make clean"
   fi

   ./configure --prefix="$install_path"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: OpenParEM failed to configure"
      exit 1
   fi

   make -j "$jobs"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: OpenParEM failed to make"
      exit 1
   fi

   make install
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: OpenParEM failed to install"
      exit 1
   fi

   make check
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: OpenParEM failed to check"
      exit 1
   fi

   cd ..
fi

# OpenParEMg
if [ "$with_OpenParEMg" = "1" ]; then

   echo "#------------------------------------------------------------------------------------"
   echo "# OpenParEM_build: OpenParEMg"
   echo "#------------------------------------------------------------------------------------"

   cd src/OpenParEMg

   rm -Rf build2
   mkdir build2
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: OpenParEMg failed to create a build directory"
      exit 1
   fi

   APP_SOURCE="$SCRIPT_DIR/../src/OpenParEMg"
   APP_BUILD="$SCRIPT_DIR/../src/OpenParEMg/build2"

   cmake -S "$APP_SOURCE" \
         -B "$APP_BUILD" \
         -DCMAKE_BUILD_TYPE=Release \
         -DCMAKE_INSTALL_PREFIX="$install_path" \
         -DCMAKE_PREFIX_PATH="$install_path" \
         || exit 1

   cmake --build "$APP_BUILD" -j"$NPROC" || exit 1

   cmake --install "$APP_BUILD" || exit 1

   cd ../..
fi

cd scripts

echo "#------------------------------------------------------------------------------------"
echo "# OpenParEM_build: creating wrappers for executables"
echo "#------------------------------------------------------------------------------------"

# see if a compiled version of Open MPI exists
cd "$install_path/bin"
   if [ $? -ne 0 ]; then
      echo "OpenParEM_ERROR: failed to change to bin directory."
      exit 1
   fi

   HAS_ORTERUN=0
   if [ -f orterun ]; then
      HAS_ORTERUN=1
   fi

   HAS_ORTERUNBIN=0
   if [ -f orterun.bin ]; then
      HAS_ORTERUNBIN=1
   fi

   HAS_MPIRUNBIN=0
   if [ -f mpirun.bin ]; then
      HAS_MPIRUNBIN=1
   fi

cd "$scripts_dir"

if [ "$with_OpenParEM" = "1" ]; then
   #wrap_executable builder $HAS_ORTERUN 0 0
   wrap_executable OpenParEM2D $HAS_ORTERUN 0 1
   #wrap_executable process2D $HAS_ORTERUN 0 0
   #wrap_executable simplify2D $HAS_ORTERUN 0 0
   wrap_executable OpenParEM3D $HAS_ORTERUN 1 1
   #wrap_executable process3D $HAS_ORTERUN 0 0
   #wrap_executable simplify3D $HAS_ORTERUN 0 0
fi

if [ "$with_OpenParEMg" = "1" ]; then
   wrap_executable OpenParEMg $HAS_ORTERUN 1 1
fi


# find which MPI library is being used
HAS_OPENMPI=0
HAS_MPICH=0
which mpirun > /dev/null 2>&1
if [ $? -eq 0 ]; then
   output=$(mpirun --version 2>/dev/null)

   echo "$output" | grep -qi "Open MPI"
   if [ $? -eq 0 ]; then
      HAS_OPENMPI=1
   fi

   echo "$output" | grep -qi "MPICH"
   if [ $? -eq 0 ]; then
      HAS_MPICH=1
   fi
fi

# wrapping for OpenMPI
if [ "$HAS_OPENMPI" = "1" ]; then 
   if [ "$HAS_ORTERUN" = "1" ]; then
      if [ "$HAS_ORTERUNBIN" = "0" ]; then
         wrap_executable orterun $HAS_ORTERUN 0 0
      fi
   else
      cd "$install_path/bin"
      if [ $? -ne 0 ]; then
         echo "OpenParEM_ERROR: failed to change to bin directory."
         exit 1
      fi

      if [ ! -f orterun ]; then

         rm -f mpirun
         echo "#!/bin/sh" > mpirun
         if [ $? -ne 0 ]; then
            echo "OpenParEM_ERROR: failed to create file mpirun."
            exit 1
         fi

         echo 'export OMP_NUM_THREADS=1' >> mpirun
         echo 'orterun "$@"' >> mpirun

      fi

      cd "$scripts_dir"
   fi
fi

# wrapping for MPICH
if [ "$HAS_MPICH" = "1" ]; then
   if [ "$HAS_MPIRUNBIN" = "0" ]; then
      wrap_executable mpirun 0 0 0
   fi
fi

# finish up with elapsed time
end_time="$(date -u +%s)"
elapsed=$(( end_time - start_time ))
echo "OpenParEM_build elapsed time (s): $elapsed"

exit 0
